apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: alb-eks-green-tg-orange
  namespace: blue-green-ns-v2
spec:
  serviceRef:
    name: blue-service # 目标对应service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:959545103699:targetgroup/orange-test/b698f4d1df193d23
